# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spada/CLionProjects/CS455_Mandelbrot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spada/CLionProjects/CS455_Mandelbrot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spada/CLionProjects/CS455_Mandelbrot/CMakeFiles /home/spada/CLionProjects/CS455_Mandelbrot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spada/CLionProjects/CS455_Mandelbrot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simpleGraphics

# Build rule for target.
simpleGraphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simpleGraphics
.PHONY : simpleGraphics

# fast build rule for target.
simpleGraphics/fast:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/build
.PHONY : simpleGraphics/fast

graphics_utilities.o: graphics_utilities.c.o

.PHONY : graphics_utilities.o

# target to build an object file
graphics_utilities.c.o:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/graphics_utilities.c.o
.PHONY : graphics_utilities.c.o

graphics_utilities.i: graphics_utilities.c.i

.PHONY : graphics_utilities.i

# target to preprocess a source file
graphics_utilities.c.i:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/graphics_utilities.c.i
.PHONY : graphics_utilities.c.i

graphics_utilities.s: graphics_utilities.c.s

.PHONY : graphics_utilities.s

# target to generate assembly for a file
graphics_utilities.c.s:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/graphics_utilities.c.s
.PHONY : graphics_utilities.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/main.c.s
.PHONY : main.c.s

xwindows_utilities.o: xwindows_utilities.c.o

.PHONY : xwindows_utilities.o

# target to build an object file
xwindows_utilities.c.o:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/xwindows_utilities.c.o
.PHONY : xwindows_utilities.c.o

xwindows_utilities.i: xwindows_utilities.c.i

.PHONY : xwindows_utilities.i

# target to preprocess a source file
xwindows_utilities.c.i:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/xwindows_utilities.c.i
.PHONY : xwindows_utilities.c.i

xwindows_utilities.s: xwindows_utilities.c.s

.PHONY : xwindows_utilities.s

# target to generate assembly for a file
xwindows_utilities.c.s:
	$(MAKE) -f CMakeFiles/simpleGraphics.dir/build.make CMakeFiles/simpleGraphics.dir/xwindows_utilities.c.s
.PHONY : xwindows_utilities.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... simpleGraphics"
	@echo "... edit_cache"
	@echo "... graphics_utilities.o"
	@echo "... graphics_utilities.i"
	@echo "... graphics_utilities.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... xwindows_utilities.o"
	@echo "... xwindows_utilities.i"
	@echo "... xwindows_utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

